// Motivational quotes shown on the workout screen, rotated daily.
// See dailyQuote() in screens/Workout.tsx — rotation period equals this array's length.
export const QUOTES = [
  "The only bad workout is the one that didn’t happen.",
  "Discipline is choosing between what you want now and what you want most.",
  "Strength doesn’t come from what you can do. It comes from overcoming what you couldn’t.",
  "Small steps every day.",
  "You don’t have to be extreme, just consistent.",
  "You won’t always be motivated. That’s why you build the habit.",
  "The body achieves what the mind believes.",
  "Don’t count the days. Make the days count.",
  "Strong is something you become, not something you’re born.",
  "Progress, not perfection.",
  "Your only limit is you.",
  "One more rep. One more set. One more day.",
  "Rest, but never quit.",
  "Be stronger than your excuses.",
  "Show up for yourself, even when no one’s watching.",
  "The pain you feel today is the strength you feel tomorrow.",
  "Success starts with self-discipline.",
  "You’re one workout away from a better mood.",
  "Doubt kills more dreams than failure ever will.",
  "The work you do today is a promise to your future self.",
  "Fall in love with taking care of yourself.",
  "Your future self is watching you right now.",
  "Earn it. Every single day.",
  "Make yourself proud.",
  "Comfort is the enemy of progress.",
  "Sore today, strong tomorrow.",
  "The hardest lift of all is lifting yourself off the couch.",
  "Excuses don’t burn calories.",
  "If it doesn’t challenge you, it won’t change you.",
  "Stop wishing. Start doing.",
  "A one-hour workout is four percent of your day. No excuses.",
  "You don’t find willpower. You build it.",
  "Showing up tired still counts.",
  "The body is a reflection of your lifestyle.",
  "Push yourself, because no one else is going to do it for you.",
  "It never gets easier. You just get stronger.",
  "Don’t limit your challenges. Challenge your limits.",
  "Good things come to those who sweat.",
  "Compare your reps to yesterday, not to anyone else.",
  "What seems impossible today will one day be your warm-up.",
  "Be the energy you want to attract.",
  "Hard work beats talent when talent doesn’t work hard.",
  "You can have results or excuses. Not both.",
  "The only way to finish is to start.",
  "Take care of your body. It’s the only place you have to live.",
  "Believe you can and you’re halfway there.",
  "Done is better than perfect.",
  "Every rep counts. Every step matters.",
  "Motivation gets you started. Habit keeps you going.",
  "Slow progress is still progress.",
  "Your body can stand almost anything. It’s your mind you have to convince.",
  "Today’s effort is tomorrow’s strength.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Dream big. Work hard. Stay focused.",
  "The clock is ticking. Are you becoming who you want to be?",
  "Energy and persistence conquer all things.",
  "Fitness is not about being better than someone else. It’s about being better than you used to be.",
  "Some people want it to happen. Some wish it would. Others make it happen.",
  "Nothing will work unless you do.",
  "Suffer the pain of discipline or suffer the pain of regret.",
  "Wake up with determination. Go to bed with satisfaction.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wish for it. Work for it.",
  "Recovery is part of the work, not a break from it.",
  "You are far more capable than you think.",
  "Results happen over time, not overnight.",
  "The hardest part is already behind you: you showed up.",
  "Build the body that carries you, not the one that impresses strangers.",
  "When you feel like quitting, remember why you started.",
  "A little progress each day adds up to big results.",
  "You’re not behind. You’re just getting started.",
  "Be obsessed with becoming the best version of yourself.",
  "Discipline is the bridge between goals and accomplishment.",
  "Stronger every day.",
  "Consistency is just discipline you stopped noticing.",
  "Your health is an investment, not an expense.",
  "Fitness is not a destination. It’s a way of life.",
  "Every session is a vote for who you’re becoming.",
  "Quit slacking and make things happen.",
  "Tough times don’t last. Tough people do.",
  "The only place where success comes before work is in the dictionary.",
  "Your pace is still progress.",
  "Set a goal that makes you want to jump out of bed in the morning.",
  "Grind now. Shine later.",
  "Be a warrior, not a worrier.",
  "Act like a champion. Train like an underdog.",
  "Pain is temporary. Pride is forever.",
  "Stay consistent and the results will come.",
  "Fight for it. Nobody said it would be easy.",
  "The will to win means nothing without the will to prepare.",
  "Great things never came from comfort zones.",
  "Sweat, smile, repeat.",
  "Your only competition is who you were yesterday.",
  "Work hard in silence. Let success make the noise.",
  "Stay patient and trust the process.",
  "Strength grows in the moments you think you can’t go on but keep going anyway.",
  "Today I will do what others won’t, so tomorrow I can do what others can’t.",
  "Push harder than yesterday if you want a different tomorrow.",
  "Make it happen. Shock everyone.",
];
