name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-backend-reusable.yml
    with:
      github-environment: production
      eb-environment: gear-fitness-env-2
    secrets: inherit
